Repository XSiling/CSE210-Project, pull requests merged in 2023-12, with the labels that each got.

#63 Further beautified Login/Register UI
  src/components/interests.js
  src/script.js
  src/style/styles.css
  src/view/login.html
  src/view/register.html
Labels: enhancement, fronted

#65 Updated README.md to include interests
  README.md
Labels: documentation

#67 hotfix dangling catch
  src/script.js
Labels: bug

#66 Added Linter to GitHub Actions
  .eslintrc.js
  .github/workflows/eslint.yml
  package-lock.json
  package.json
Labels: enhancement

#82 Add jsdocs for server and script
  package-lock.json
  src/script.js
  src/server.js
Labels: documentation

#110 Login/Register Enhancements
  src/script.js
  src/style/styles.css
  src/view/login.html
  src/view/register.html
Labels: enhancement, fronted

#112 update follow function to recommend people
  package-lock.json
  package.json
  src/components/account.js
  src/components/card.css
  src/components/card.js
  src/components/interests.js
  src/components/post.css
  src/components/post.js
  src/components/recommendation.js
  src/images/63457.jpg
  src/images/default.png
  src/images/logo.jpg
  src/mastodonApi/mastodonApi.py
  src/script.js
  src/server.js
  src/style/recommendation.css
  src/style/styles.css
  src/view/interests.html
  src/view/login.html
  src/view/recommendations.html
  src/view/register.html
Labels: bug, enhancement, backend, fronted, recommendation

#119 update alert and edge case for mastodon account input
  src/components/recommendation.js
  src/images/user-image/profile-predefined-img-1.png
  src/images/user-image/profile-predefined-img-10.png
  src/images/user-image/profile-predefined-img-11.png
  src/images/user-image/profile-predefined-img-12.png
  src/images/user-image/profile-predefined-img-2.png
  src/images/user-image/profile-predefined-img-3.png
  src/images/user-image/profile-predefined-img-4.png
  src/images/user-image/profile-predefined-img-5.png
  src/images/user-image/profile-predefined-img-6.png
  src/images/user-image/profile-predefined-img-7.png
  src/images/user-image/profile-predefined-img-8.png
  src/images/user-image/profile-predefined-img-9.png
  src/script.js
  src/server.js
  src/view/recommendations.html
Labels: bug, enhancement, backend, fronted

#136 update to lower the latency and fix the bug
  package-lock.json
  package.json
  src/components/account.js
  src/components/card.js
  src/components/post.js
  src/components/recommendation.js
  src/images/loading-1.svg
  src/images/loading-2.svg
  src/script.js
  src/server.js
  src/style/recommendation.css
  src/view/recommendations.html
Labels: enhancement, backend, fronted, recommendation

#138 fixes to README
  README.md
Labels: documentation

#141 refactor config files
  .github/workflows/blank.yml
  .github/workflows/eslint.yml
  README.md
  configs/.babelrc
  configs/.eslintrc.js
  configs/jest.config.js
  configs/requirements.txt
Labels: enhancement

#148 remove debug logs
  src/components/account.js
  src/components/card.js
  src/components/interests.js
  src/components/profile.js
  src/components/recommendation.js
  src/script.js
  src/server.js
Labels: enhancement

#152 add additional tests
  src/server.js
  tests/logout.test.js
  tests/proxy.test.js
Labels: backend

#153 add minor backend tests
  tests/follow.test.js
  tests/server.test.md
Labels: backend

#154 Updated jsdoc for script.js
  src/script.js
Labels: documentation
